### ISSUE TITLE
Fails to install Playwright MCP Server

### ISSUE THREAD

**Issue by ichoosetoaccept** [smithery-ai/typescript-sdk#10]
I tried to install this using Smithery: https://github.com/executeautomation/mcp-playwright

Here's what happened:

npx @smithery/cli install @executeautomation/playwright-mcp-server --client claude
Need to install the following packages:
@smithery/cli@0.0.22
Ok to proceed? (y) y

Generating configuration for: @executeautomation-playwright-mcp-server
Failed to install package: Error: Failed to fetch server configuration. Please report to: https://github.com/smithery-ai/typescript-sdk/issues/new?labels=bug
    at Rse (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:65:2439)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _o (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:65:3872)
    at async sS (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:70:769)
    at async o0e (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:78:542)
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: Failed to fetch server configuration. Please report to: https://github.com/smithery-ai/typescript-sdk/issues/new?labels=bug
    at Rse (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:65:2439)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _o (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:65:3872)
    at async sS (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:70:769)
    at async o0e (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:78:542)

Node.js v23.5.0

**Comment by calclavia** [comment]
> I tried to install this using Smithery: https://github.com/executeautomation/mcp-playwright
> 
> Here's what happened:
> 
> npx @smithery/cli install @executeautomation/playwright-mcp-server --client claude Need to install the following packages: @smithery/cli@0.0.22 Ok to proceed? (y) y
> 
> Generating configuration for: @executeautomation-playwright-mcp-server Failed to install package: Error: Failed to fetch server configuration. Please report to: https://github.com/smithery-ai/typescript-sdk/issues/new?labels=bug at Rse (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:65:2439) at process.processTicksAndRejections (node:internal/process/task_queues:105:5) at async _o (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:65:3872) at async sS (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:70:769) at async o0e (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:78:542) node:internal/process/promises:394 triggerUncaughtException(err, true /* fromPromise */); ^
> 
> Error: Failed to fetch server configuration. Please report to: https://github.com/smithery-ai/typescript-sdk/issues/new?labels=bug at Rse (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:65:2439) at process.processTicksAndRejections (node:internal/process/task_queues:105:5) at async _o (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:65:3872) at async sS (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:70:769) at async o0e (/Users/ismar/.npm/_npx/2d0620bb1d41b604/node_modules/@smithery/cli/dist/index.js:78:542)
> 
> Node.js v23.5.0

Thanks for reporting. Just fixed with latest build - let me know if there are any further issues.
